### PR TITLE
Add support for Swift Package Manager (SPM)

### PR DESCRIPTION
**Pull request by iKenndac**
This is just a case of adding a `Package.swift` file and creating an `xcframework` structure with the Paddle framework within. This can be done from the existing framework like this: 

```
xcodebuild -create-xcframework -framework Paddle.framework -output Paddle.xcframework
```

Please add this to the main repo — it'd be very useful for a lot of developers, and would stop us having to maintain a fork.

### CODE REVIEW

**Comment by mkk** [comment]
It would be super useful to use it as swift package. I have many projects that use Paddle and using SwiftPM would speed up integration a lot

**Comment by iKenndac** [comment]
It's very disappointing that SPM support still hasn't been added despite how easy it is to add and how long ago I've requested this both via this repo and Paddle's official seller support channels. I've updated our fork with SPM support for the newest release.

**Comment by kwokaaron** [comment]
Hello @iKenndac, I hope you're doing well. This has now been added to the new release that was pushed today, thanks!

**Comment by iKenndac** [comment]
Hooray! Thank you!

**Pull request closed without merging**
